name: 'Rust Release binary'
description: 'Automate publishing Rust build artifacts for GitHub releases through GitHub Actions'
inputs:
  RUSTTARGET:
    description: 'Output target'
    required: true
  SRC_DIR:
    description: 'Path to directory containing Cargo.toml (defaults to project root)'
    required: false
  NIGHTLY:
    description: 'Use the nightly Rust toolchain'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
